### ISSUE TITLE
Lack of Dataset

### ISSUE THREAD

**Issue by hisakot** [chihina/PJAE-ICCV2023#3]
Hello, 

I have read your paper and I am interested in your work.
I wanted to run the volleyball dataset's demo code, but an error happened:
> No` such file or directory: data/vatic_ball_annotation/annotation_data_sub/volleyball_4_105655_ver3.csv'

I have downloaded all of the datasets from this Google Drive link: https://drive.google.com/drive/folders/1O55_wri92uv87g-2aDh8ll6dFVupmFaB?usp=share_link, but I cannot find "vatic_ball_annotation/annotation_data".

I would like to know where to find the annotated data. 

(I also faced the dimension error in the VideoCoAtt dataset's demo code, but it is similar to another issue, so I will try to fix it with the same strategy.)

**Comment by chihina** [comment]
Hello,

Thank you for reading our paper!
These annotation files (e.g., volleyball_4_105655_ver3.csv) can be found in annotation_data.zip.
Please unzip the file and set the directory name in yaml files (the variable name is 'data: annotation_dir')

Thank you

**Comment by hisakot** [comment]
Thank you for your prompt reply.
I could pass through the dataset issue.
I misunderstood there was a file called vatic_ball_annotation.

Thank you.

**Comment by hisakot** [comment]
Also, I have another error:

> Traceback (most recent call last):
  File "/home/hisakot/Lab/PJAE-ICCV2023/demo_ours.py", line 283, in <module>
    out_attention = model_attention(batch)
  File "/home/hisakot/Lab/PJAE-ICCV2023/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hisakot/Lab/PJAE-ICCV2023/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hisakot/Lab/PJAE-ICCV2023/models/joint_attention_estimator_transformer_dual.py", line 293, in forward
    trans_att_people_people_i = people_people_trans_weights.view(self.batch_size, 1, people_num+1, people_num+1)
RuntimeError: shape '[1, 1, 4, 4]' is invalid for input of size 169

I would like to know more about this error.

**Comment by chihina** [comment]
Which a yaml file did you use to run?

**Comment by hisakot** [comment]
I used yaml/volleyball/demo.yaml file.

**Comment by chihina** [comment]
The error does not happen in my codes.
Could you tell me more details?
1. What model did you use?
2. What command did you run? (e.g, python demo_ours.py yaml/volleyball/demo.yaml)
3. Did you edit the provided codes?

Thank you.

**Comment by hisakot** [comment]
OK.

1. model: 
I used "volleyball-dual-mid_p_p_field_middle_p_s_davt_bbox_GT_gaze_GT_act_GT_weight_fusion_fine_token_only" file's model, which I downloaded from Google Drive and put under "saved_weights" folder.

2. commnamd: 
I used this,
> python3 demo_ours.py yaml_files/volleyball/demo.yaml

it follows README 4.1(I changed yaml→yaml_files)

3. code editing: 
I have only changed the directory name of the config obtained from your response regarding the dataset.

> annotation_dir : data/vatic_ball_annotation/annotation_data
→annotation_dir : data/annotation_data
(in yaml_files/volleyball/demo.yaml)

**Comment by chihina** [comment]
I cannot find out why the error occurs because it does not occur in my environment. However, I refactored demo_our.py, so could you kindly run the command again after pulling the latest codes?

**Comment by hisakot** [comment]
Thank you for updating codes, but the same error occured at the same point...

**Comment by chihina** [comment]
Could you paste the error again?

**Comment by hisakot** [comment]
After I replaced all of codes (not only demo.py), the shape error was done.

Then, I faced another value error:

> Traceback (most recent call last):
  File "/home/hisakot/Lab/PJAE-ICCV2023/demo_ours_re.py", line 255, in <module>
    out_head = model_head(batch)
  File "/home/hisakot/Lab/PJAE-ICCV2023/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hisakot/Lab/PJAE-ICCV2023/env/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hisakot/Lab/PJAE-ICCV2023/models/head_pose_estimator.py", line 38, in forward
    batch_size, people_num, channel_num, img_height, img_width = head_img.shape
ValueError: too many values to unpack (expected 5)

**Comment by chihina** [comment]
It seems the code is not updated to the latest code because the line 38 of head_pose_estimator.py in the error is different from https://github.com/chihina/PJAE-ICCV2023/blob/master/models/head_pose_estimator.py.

**Comment by hisakot** [comment]
Thank you!
By replacing head_pose_estimator.py, the whole thing worked fine!

Thank you very much for your long time and kind cooperation!
